networks:
  proxy:
  traefik:
  outline:

x-common-service: &common-service
  restart: unless-stopped

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 10s
  retries: 5
  start_period: 5s

services:
  socket-proxy:
    <<: *common-service
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    #image: ghcr.io/tecnativa/docker-socket-proxy:0.1
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:2375/version"]
      <<: *common-healthcheck
    privileged: true
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
    networks:
      - proxy

  traefik:
    <<: *common-service
    image: docker.io/library/traefik:banon
    #image: docker.io/library/traefik:3.0
    depends_on:
      - socket-proxy
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      <<: *common-healthcheck
    command:
      - --accesslog=true
      - --accesslog.filepath=/access.log
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.network=traefik
      - --providers.docker.defaultRule=Host(`{{ . Name }}.${DOMAIN}:${PORT}`)
      - --entrypoints.https.address=:${PORT}
      #- --entrypoints.https.asdefault=true
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN}:${PORT}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN}:${PORT}
      - --global.checknewversion=false
      - --log=true
      - --log.level=WARN
    volumes:
      - ${DATA_DIR}/access.log:/access.log:Z
    networks:
      - proxy
      - traefik

  outline:
    <<: *common-service
    image: docker.getoutline.com/outlinewiki/outline:latest
    #image: docker.getoutline.com/outlinewiki/outline:0.76.1
    depends_on:
      - outline-db
      - outline-redis
      - diagrams
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3000"]
      <<: *common-healthcheck
    environment:
      URL: https://outline.${DOMAIN}:${PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@outline-db:5432/${POSTGRES_DB}
      PGSSLMODE: disable
      REDIS_URL: redis://outline-redis:6379
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 262144000
      OIDC_AUTH_URI: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
      OIDC_TOKEN_URI: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      OIDC_USERINFO_URI: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
      OIDC_LOGOUT_URI: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/logout
      OIDC_USERNAME_CLAIM: preferred_username
      OIDC_DISPLAY_NAME: OpenID Connect
      OIDC_SCOPES: openid profile email
      OIDC_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      FORCE_HTTPS: "false"
      ENABLE_UPDATES: "false"
      DEFAULT_LANGUAGE: en_US
      NODE_ENV: production
      RATE_LIMITER_ENABLED: "false"
      LOG_LEVEL: ${OUTLINE_LOG_LEVEL}
      WEB_CONCURRENCY: ${OUTLINE_WEB_CONCURRENCY}
      SECRET_KEY: ${OUTLINE_SECRET_KEY}
      UTILS_SECRET: ${OUTLINE_UTILS_SECRET}
    volumes:
      - ${DATA_DIR}/outline-storage:/var/lib/outline/data:Z
    labels:
      - traefik.enable=true
    networks:
      - traefik
      - outline

  outline-db:
    <<: *common-service
    image: docker.io/library/postgres:latest
    #image: docker.io/library/postgres:16.3
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      <<: *common-healthcheck
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_DIR}/outline-db:/var/lib/postgresql/data:Z
    networks:
      - outline

  outline-redis:
    <<: *common-service
    image: docker.io/library/redis:latest
    #image: docker.io/library/redis:7.2
    healthcheck:
      test: ["CMD-SHELL", "$$(redis-cli ping) == 'PONG'"]
      <<: *common-healthcheck
    networks:
      - outline

  diagrams:
    <<: *common-service
    image: docker.io/jgraph/drawio:latest
    #image: docker.io/jgraph/drawio:24.4.4
    depends_on:
      - diagrams-export
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080"]
      <<: *common-healthcheck
    environment:
      DRAWIO_SELF_CONTAINED: 1
      DRAWIO_USE_HTTP: 1
      DRAWIO_BASE_URL: https://diagrams.${DOMAIN}:${PORT}
      EXPORT_URL: https://diagrams-export.${DOMAIN}:${PORT}
    labels:
      - traefik.enable=true
    networks:
      - traefik

  diagrams-export:
    <<: *common-service
    image: docker.io/jgraph/export-server:latest
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000"]
      <<: *common-healthcheck
    environment:
      DRAWIO_BASE_URL: https://diagrams.${DOMAIN}:${PORT}
    labels:
      # TODO: test how this should be exposed
      - traefik.enable=true
    networks:
      - traefik
